version: '3'

services:
  darkweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901:6080"
    environment:
      - VNC_USER=user
      - VNC_PW=password
    container_name: darkweb